let products = [
  {
    id: 1,
    name: "iPhone 15",
    brand: "Apple",
    category: "Mobile",
    price: 79900,
    originalPrice: 89900,
    discount: "11%",
    inStock: true,
    stockQuantity: 18,
    rating: 4.8,
    reviews: 1240,
    color: "Black",
    warranty: "1 year manufacturer warranty",
    features: ["A16 Bionic Chip", "128GB Storage", "48MP Main Camera", "USB-C Charging"],
    description: "A premium smartphone with a powerful chip, bright display, and advanced camera system.",
    image: "https://source.unsplash.com/400x400/?iphone"
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    category: "Mobile",
    price: 74999,
    originalPrice: 84999,
    discount: "12%",
    inStock: true,
    stockQuantity: 22,
    rating: 4.7,
    reviews: 980,
    color: "Cobalt Violet",
    warranty: "1 year manufacturer warranty",
    features: ["Dynamic AMOLED Display", "256GB Storage", "50MP Camera", "Fast Charging"],
    description: "A flagship Android phone with a sharp display, smooth performance, and AI-powered camera tools.",
    image: "https://source.unsplash.com/400x400/?samsung-phone"
  },
  {
    id: 3,
    name: "Sony WH-1000XM5 Headphones",
    brand: "Sony",
    category: "Audio",
    price: 29990,
    originalPrice: 34990,
    discount: "14%",
    inStock: true,
    stockQuantity: 12,
    rating: 4.9,
    reviews: 845,
    color: "Silver",
    warranty: "1 year warranty",
    features: ["Noise Cancellation", "Bluetooth 5.2", "30 Hours Battery", "Quick Charge"],
    description: "Wireless headphones built for high-quality sound, long battery life, and excellent noise cancellation.",
    image: "https://source.unsplash.com/400x400/?headphones"
  },
  {
    id: 4,
    name: "Dell Inspiron 15 Laptop",
    brand: "Dell",
    category: "Laptop",
    price: 65999,
    originalPrice: 72999,
    discount: "10%",
    inStock: true,
    stockQuantity: 9,
    rating: 4.5,
    reviews: 560,
    color: "Platinum Silver",
    warranty: "1 year onsite warranty",
    features: ["Intel Core i5", "16GB RAM", "512GB SSD", "15.6 inch Full HD Display"],
    description: "A reliable everyday laptop for study, office work, browsing, and entertainment.",
    image: "https://source.unsplash.com/400x400/?laptop"
  },
  {
    id: 5,
    name: "Nike Air Zoom Pegasus",
    brand: "Nike",
    category: "Footwear",
    price: 8995,
    originalPrice: 10995,
    discount: "18%",
    inStock: true,
    stockQuantity: 35,
    rating: 4.6,
    reviews: 430,
    color: "White and Blue",
    warranty: "6 months warranty",
    features: ["Running Shoes", "Lightweight Design", "Breathable Mesh", "Cushioned Sole"],
    description: "Comfortable running shoes designed for daily training, walking, and active use.",
    image: "https://source.unsplash.com/400x400/?running-shoes"
  },
  {
    id: 6,
    name: "Apple Watch Series 9",
    brand: "Apple",
    category: "Wearable",
    price: 41900,
    originalPrice: 45900,
    discount: "9%",
    inStock: false,
    stockQuantity: 0,
    rating: 4.8,
    reviews: 760,
    color: "Midnight",
    warranty: "1 year manufacturer warranty",
    features: ["Heart Rate Monitor", "GPS", "Water Resistant", "Always-On Retina Display"],
    description: "A smart watch for health tracking, notifications, workouts, and daily productivity.",
    image: "https://source.unsplash.com/400x400/?smartwatch"
  },
  {
    id: 7,
    name: "Canon EOS 1500D DSLR Camera",
    brand: "Canon",
    category: "Camera",
    price: 45999,
    originalPrice: 49999,
    discount: "8%",
    inStock: true,
    stockQuantity: 7,
    rating: 4.4,
    reviews: 315,
    color: "Black",
    warranty: "2 years warranty",
    features: ["24.1MP Sensor", "Full HD Video", "WiFi Support", "18-55mm Lens"],
    description: "A beginner-friendly DSLR camera for photography, travel, portraits, and video recording.",
    image: "https://source.unsplash.com/400x400/?dslr-camera"
  },
  {
    id: 8,
    name: "JBL Flip 6 Bluetooth Speaker",
    brand: "JBL",
    category: "Audio",
    price: 9999,
    originalPrice: 11999,
    discount: "17%",
    inStock: true,
    stockQuantity: 26,
    rating: 4.6,
    reviews: 690,
    color: "Red",
    warranty: "1 year warranty",
    features: ["Portable Speaker", "Waterproof", "12 Hours Battery", "Bass Boost"],
    description: "A compact portable speaker with strong bass, durable build, and outdoor-ready battery life.",
    image: "https://source.unsplash.com/400x400/?bluetooth-speaker"
  },
  {
    id: 9,
    name: "Logitech G502 Gaming Mouse",
    brand: "Logitech",
    category: "Accessories",
    price: 4495,
    originalPrice: 5995,
    discount: "25%",
    inStock: true,
    stockQuantity: 40,
    rating: 4.7,
    reviews: 520,
    color: "Black",
    warranty: "2 years warranty",
    features: ["RGB Lighting", "25600 DPI Sensor", "Programmable Buttons", "Ergonomic Grip"],
    description: "A precise gaming mouse with customizable controls, fast tracking, and comfortable handling.",
    image: "https://source.unsplash.com/400x400/?gaming-mouse"
  },
  {
    id: 10,
    name: "Green Soul Ergonomic Office Chair",
    brand: "Green Soul",
    category: "Furniture",
    price: 11999,
    originalPrice: 15999,
    discount: "25%",
    inStock: false,
    stockQuantity: 0,
    rating: 4.3,
    reviews: 275,
    color: "Black",
    warranty: "3 years warranty",
    features: ["Adjustable Height", "Lumbar Support", "Mesh Back", "Reclining Seat"],
    description: "A comfortable office chair built for long study sessions, work-from-home setups, and desk use.",
    image: "https://source.unsplash.com/400x400/?office-chair"
  }
];
